### ISSUE TITLE
No module named 'unfoldNd'

### ISSUE THREAD

**Issue by Sihao** [cabooster/SRDTrans#1]
'sampling.py' is importing this, I assume it is some sort of helper function that is missing and not a package?

**Comment by a-jacobo** [comment]
unfoldNd is a python package, but it's missing in requirements.txt. You can solve it by doing `pip install unfoldNd`

**Comment by Huxiaowan** [comment]
Hello, I am sorry that some debugging packages such as unfoldNd were mistakenly included in the release code. You can install them with pip, and we will solve this problem in the latest version.
