### ISSUE TITLE
Can this method implemented on still images

### ISSUE THREAD

**Issue by Danielement321** [cabooster/SRDTrans#12]
Thanks for your outstanding work!
I met some problems when I attempted this method on the FMD dataset, which contains only common PNG grayscale photos.
The traceback is as follows, I used the test-mix set which contains different grayscale images and I have transformed them into TIFF format.
Thanks again for your kind reply.

(srdtrans) root@Daniel-Desktop:~/SRDTrans# python train.py --datasets_folder noisy --n_epochs 20 --GPU 0 --train_dataset
s_size 6000  --patch_x 160 --patch_t 160
Training parameters ----->
Namespace(GPU='0', b1=0.5, b2=0.999, batch_size=1, datasets_folder='noisy', datasets_path='datasets', gap_t=80, gap_x=80, gap_y=80, lr=0.0001, n_epochs=20, ngpu=1, output_path='./results', overlap_factor=0.5, patch_t=160, patch_x=160, patch_y=160, pth_path='./pth', scale_factor=1, select_img_num=10000000000, test_datasize=10000000000, train_datasets_size=6000)
ckp is saved in pth/noisy_202411051009
Image list for training ----->
All files are in ----->  datasets/noisy
Total stack number ----->  48
Reading files...
Please check the shape of these image stacks, since some hyperstacks have unusual shapes. In that case, you just need to re-store these images by ImageJ.
WideField_BPAE_B_3.tiff  -----> the shape is (512, 512)
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train_name_list, train_noise_img, train_coordinate_list, stack_index = train_preprocess_lessMemoryMulStacks(opt)
  File "/root/SRDTrans/data_process.py", line 217, in train_preprocess_lessMemoryMulStacks
    gap_t = get_gap_t(args, noise_im, stack_num)
  File "/root/SRDTrans/data_process.py", line 169, in get_gap_t
    whole_x = img.shape[2]
IndexError: tuple index out of range

**Comment by cabooster** [comment]
Hi Danielement. SRDTrans was designed for fluorescence time-lapse imaging. If you want to apply it to still images, you can duplicate it into a stack of 300-500 images. Then SRDTrans can be used to process it.
