### ISSUE TITLE
Question to the Gif in the readme text

### ISSUE THREAD

**Issue by BlueDayz** [cabooster/SRDTrans#2]
Hello SRDTrans team,
Great project and associated paper you created here. I just wonder how you generated the nice Gif in the ReadMe document. 
I would like to know which package or technique you used for this comparison of the before after image !:) 

Greetings

**Comment by Huxiaowan** [comment]
Hello, thank you for recognizing our work. 

First, no special operation is required to insert the Gif file into the readme file, you only need to insert the made gif file into the corresponding position as an image, details can be found from the source code of readme file.

 Besides, the image comparison is done by Fiji software, you can crop the same patch of the images.
