### ISSUE TITLE
data process of 16bit(tiff)

### ISSUE THREAD

**Issue by Yisher** [cabooster/SRDTrans#7]
hello！I am so excited of this wonderful work for SMLM denoising .And I noticed that you guys can deal the dataset as 16bit. But I remember pytorch can not deal with  uint16 data, can you help me to realize how your data loader runs for 16bit data?

**Comment by Huxiaowan** [comment]
Thank you for supporting our work.
During the training phase, we convert the input data type to float32 before participating in subsequent operations. Please refer to L209-L222 in _data_process.py._ And in the inference phase, we reconvert the storage type to the original data type to ensure the consistency of input and output, please refer to L223-L238 in _test.py_.

**Comment by wu99271053** [comment]
Hi! thank you very much for your work! i am curious about the scale factor you used in training the model. when i use the default scaling factor (which is 1) , my loss is way too large.

**Comment by cabooster** [comment]
The scale factor is used to compress the range of data. I think the default value is OK if no error occurs.
