### ISSUE TITLE
Example on using model unclear

### ISSUE THREAD

**Issue by BioTurboNick** [cabooster/SRDTrans#8]
Thank you for this nice package.

One step in the example that is unclear is what output from the training is used for the model. The Inference section shows specifying a folder containing models using `--denoise-model`, but what should the contents of the folder be? All of the contents of the `pth` folder? Just the last epoch? If there are multiple models in that folder, what governs selection?

I will appreciate your added clarity :-)

**Comment by BioTurboNick** [comment]
I tried just pointing to the `pth` folder and got this error:

```
Traceback (most recent call last):
  File "/home/nicho/SRDTrans/test.py", line 59, in <module>
    model_list = list(os.walk(model_path, topdown=False))[-1][-1]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by BioTurboNick** [comment]
Okay, I see what is intended - it's supposed to be the subfolder **in** `pth`.

So here, the whole path was `pth/noisy_202401250824`, and the argument needed to be `noisy_202401250824`.

I would recommend the documentation/help text be adjusted to specify that it's intended to be the name of the subfolder in `pth`.

**Comment by cabooster** [comment]
Thanks for your suggestion. We will make it clear in ReadMe.
